# Generated by Django 3.0.8 on 2020-08-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('bibliografia', models.CharField(max_length=400)),
                ('foto', models.ImageField(upload_to='')),
                ('fecha_nacimiento', models.DateTimeField()),
                ('fecha_defuncion', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'carga',
                'verbose_name_plural': 'cargas',
            },
        ),
    ]
